---
baseURL: https://benmerde.com
languageCode: fr-fr
title: Ben Merde
MetaDataFormat: yaml
pagination:
  pagerSize: 10
disqusShortname: ben-merde
outputs:
  home: [HTML, RSS, Algolia]
  page: [HTML]
  section: [HTML]
params:
  area: canada
  authorname: John Doe
  description: je suis au Canada
  facebookid: 137223813025796
  aws_url: https://s3.us-east-2.amazonaws.com/media.benmerde.com

  twitter_handle: benmerde

  imagesizes:
    '500': small
    '750': medium
build:
  cachebusters:
    - source: scss
      target: css
taxonomies:
  location: locations
  event: events
permalinks:
  post: "/:year/:month/:title/"
  item: '/projet202/objets-du-jour/:slug/'
  events: 'projet/:slug'

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

imaging:
  quality: 90