---
baseURL: https://benmerde.com
languageCode: fr-fr
title: Ben Merde
MetaDataFormat: yaml
theme: benmerde
paginate: 10
disqusShortname: ben-merde

outputs:
  home: [HTML, RSS, Algolia]
  page: [HTML]
params:
  area: canada
  authorname: John Doe
  description: je suis au Canada
  facebookid: 137223813025796
  aws_url: https://s3.us-east-2.amazonaws.com/media.benmerde.com

  algolia:
    vars: ["title", "summary", "permalink", "relpermalink", "area", "humanDate"]
    params: ["locations", "categories"]

taxonomies:
  tag: tags
  location: locations
permalinks:
  post: "/:year/:month/:title/"
  item: '/projet202/objets-du-jour/:slug/'

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true