---
baseURL: https://benmerde.com
languageCode: fr-fr
title: Ben Merde
MetaDataFormat: yaml
theme: benmerde
paginate: 10
disqusShortname: ben-merde
params:
  area: usa
  authorname: John Doe
  description: je suis au Canada
  facebookid: 137223813025796
taxonomies:
  tag: tags
  location: locations
permalinks:
  post: "/:year/:month/:title/"
