[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.50"
  HUGO_ENV = "netlify"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.50"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.50"