---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/post/japon
  label: Japon
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/post/france
  label: France
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/post/canada
  label: Canada
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/post/usa
  label: USA
  create: documents
  match: "**/*"
  templates:
  - post
upload_dir: content/medias
public_path: "/medias"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
