---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/post/france
  label: France
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/canada
  label: Canada
  create: documents
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/usa
  label: USA
  create: documents
  match: "**/*"
  templates:
  - post
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.31.1
